### ISSUE TITLE
Apparent UB in `access_mem` and maybe others

### ISSUE THREAD

**Issue by deriamis** [libunwind/libunwind#340]
We just tried running `UndefinedBehaviorSanitizer` in our build with `tcmalloc` using `libunwind` as the unwinder, which results in this report:

```
[j0] src/third_party/unwind/dist/src/x86_64/Ginit.c:334:14: runtime error: load of misaligned address 0x7fabeb9d70ca for type 'unw_word_t' (aka 'unsigned long'), which requires 8 byte alignment
--
[j0] 0x7fabeb9d70ca: note: pointer points here
[j0]  66 f5  00 00 48 8d 15 cf f8 00  00 4c 89 ec 41 ff e4 66  0f 1f 84 00 00 00 00 00  83 47 04 01 c3 90
[j0]               ^
[j0]     #0 0x7fabe8807bc1 in access_mem /home/katwu/mongodb/mongo/src/third_party/unwind/dist/src/x86_64/Ginit.c:334:14
[j0]     #1 0x7fabe8809ada in is_plt_entry /home/katwu/mongodb/mongo/src/third_party/unwind/dist/src/x86_64/Gstep.c:43:14
[j0]     #2 0x7fabe8809ada in _ULx86_64_step /home/katwu/mongodb/mongo/src/third_party/unwind/dist/src/x86_64/Gstep.c:126
[j0]     #3 0x7fabeb6c958c in GetStackTrace_libunwind(void**, int, int) /home/katwu/mongodb/mongo/src/third_party/gperftools/dist/src/stacktrace_libunwind-inl.h:138:9
[j0]     #4 0x7fabeb6c9819 in maybe_convert_libunwind_to_generic_fp() /home/katwu/mongodb/mongo/src/third_party/gperftools/dist/src/stacktrace.cc:353:12
[j0]     #5 0x7fabeb6cada6 in init_default_stack_impl() /home/katwu/mongodb/mongo/src/third_party/gperftools/dist/src/stacktrace.cc:385:3
[j0]     #6 0x7fabeb6b41fb in (anonymous namespace)::google_init_module_stacktrace_init_default_stack_impl() /home/katwu/mongodb/mongo/src/third_party/gperftools/dist/src/stacktrace.cc:396:1
[j0]     #7 0x7fabeb6b41fb in GoogleInitializer::GoogleInitializer(char const*, void (*)(), void (*)()) /home/katwu/mongodb/mongo/src/third_party/gperftools/dist/src/base/googleinit.h:46
[j0]     #8 0x7fabeb6b41fb in __cxx_global_var_init /home/katwu/mongodb/mongo/src/third_party/gperftools/dist/src/stacktrace.cc:396
[j0]     #9 0x7fabeb6b41fb in _GLOBAL__sub_I_stacktrace.cc /home/katwu/mongodb/mongo/src/third_party/gperftools/dist/src/stacktrace.cc
[j0] Waiting to connect to mongod on port 20000.
[j0]     #10 0x7fabeb9e6732 in call_init /build/glibc-OTsEL5/glibc-2.27/elf/dl-init.c:72
[j0]     #11 0x7fabeb9e6732 in _dl_init /build/glibc-OTsEL5/glibc-2.27/elf/dl-init.c:119
[j0]     #12 0x7fabeb9d70c9  (/lib64/ld-linux-x86-64.so.2+0x10c9)
```

At least on the surface, this appears to be a valid because nothing seems to ensure that `addr` is aligned to be dereferenced as an `unsigned long`. For example:
* https://github.com/10gen/mongo/blob/0c818a98dc5634a1536818d44f23573f19e3ffbf/src/third_party/unwind/dist/src/x86_64/Ginit.c#L334
* https://github.com/10gen/mongo/blob/0c818a98dc5634a1536818d44f23573f19e3ffbf/src/third_party/unwind/dist/src/x86_64/Ginit.c#L355
* https://github.com/10gen/mongo/blob/0c818a98dc5634a1536818d44f23573f19e3ffbf/src/third_party/unwind/dist/src/x86_64/Ginit.c#L360
* https://github.com/10gen/mongo/blob/0c818a98dc5634a1536818d44f23573f19e3ffbf/src/third_party/unwind/dist/src/x86_64/Ginit.c#L387
* https://github.com/10gen/mongo/blob/0c818a98dc5634a1536818d44f23573f19e3ffbf/src/third_party/unwind/dist/src/x86_64/Ginit.c#L391

We are unsure how to address this failure because we don't know whether there is reason to assume these should result in aligned memory accesses. In any case, it clearly does not always, so we assume that whatever precondition was assumed has been violated somehow. What would be the best course of action for correcting this report?

**Comment by yuyichao** [comment]
It seems that your link points to invalid/private repo since they don't work for me.

Assuming that your are pointing to the `access_mem` function as shown in your backtrace it seems that the fix is to just replace the direct load with a `memcpy`. The compiler will take care of optimizing that to direct loads/stores.

**Comment by acmorrow** [comment]
@yuyichao - I agree, using `memcpy` for these sorts of accesses would be a suitable fix (if a fix is indeed required), and the compiler will probably end up generating the same code anyway for the small fixed size `memcpy`, if performance is a concern. The other point, about the alignment of `ucontext_t` is more interesting, and one of the reasons we filed this issue instead of just writing ourselves a suppression.

Here, for instance, is I believe a relevant invocation of `access_mem`: https://github.com/libunwind/libunwind/blob/400b3f819ad44ff4e15487b163cc3613389cb4c8/include/tdep-x86/libunwind_i.h#L148

In that call, `addr` is the result of a `DWARF_GET_LOC`, which looks at the `.val` member. Is that value also guaranteed to always have suitable alignment when interpreted as an `unw_word_t`? If so, then we probably have an error on our side (corrupt dwarf info?), but if not, maybe there is an issue on the libunwind side. Overall, it looks like there many many a instances of reading/writing through a dereferenced pointer in the libunwind codebase, not just the example ones above, so maybe our best choice really is to suppress the alignment sanitizer, rather than chase all of them down.

Still, we thought it was worth raising the issue.

Finally, @deriamis - Can you fix the above links to refer into the `libunwind` tree rather than a private repo?

**Comment by deriamis** [comment]
@acmorrow @yuyichao Sorry about that. I've fixed the links to point to this repository.
