### ISSUE TITLE
Missing frames in arm64

### ISSUE THREAD

**Issue by arthurep** [libunwind/libunwind#399]
I'm trying to get the backtrace of a malloc call done inside libopenssl using libunwind for arm64. I have noticed that every time a stacktrace goes through this library, `unw_step` stops at it and doesn't unwind any further. I did a comparison with GDB to confirm that are indeed missing frames:

```
(gdb) break CRYPTO_zalloc
Breakpoint 1 at 0x835458
(gdb) c
...
Breakpoint 1, 0x00835458 in CRYPTO_zalloc ()
(gdb) bt
#0  0x00835458 in CRYPTO_zalloc ()
#1  0x00859de4 in CRYPTO_THREAD_lock_new ()
#2  0x00832cf4 in ossl_init_base_ossl_ ()
#3  0xb61d2a10 in pthread_once () from target:/lib//libc.so.0
#4  0x00859e8c in CRYPTO_THREAD_run_once ()
#5  0x00832f80 in OPENSSL_init_crypto ()
#6  0x0092dc74 in OPENSSL_init_ssl ()
#7  0x0016079c in initialize_libraries () at src/main.cpp:322
#8  0x00161ec4 in main (argc=1, argv=0xbed81cc4) at src/main.cpp:821
```

similar stack with `unw_get_reg(IP)` & `unw_get_proc_name()`:
```
0xb6353498:  (malloc+0xe0) --> backtracing from here
0x83545c:  (CRYPTO_zalloc+0xc)
```

objdump -h of library containing `CRYPTO_zalloc`:
```
output/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libcrypto.so.1.1:     file format elf32-littlearm

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .hash         000086d8  000000f4  000000f4  000000f4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  1 .gnu.hash     00009478  000087cc  000087cc  000087cc  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .dynsym       00011b10  00011c44  00011c44  00011c44  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  3 .dynstr       000156bf  00023754  00023754  00023754  2**0
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  4 .gnu.version  00002362  00038e14  00038e14  00038e14  2**1
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  5 .gnu.version_d 00000230  0003b178  0003b178  0003b178  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  6 .gnu.version_r 00000020  0003b3a8  0003b3a8  0003b3a8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  7 .rel.dyn      00013730  0003b3c8  0003b3c8  0003b3c8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  8 .rel.plt      00000480  0004eaf8  0004eaf8  0004eaf8  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  9 .init         00000010  0004ef78  0004ef78  0004ef78  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 10 .plt          000006d4  0004ef88  0004ef88  0004ef88  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 11 .text         00133474  00050000  00050000  00050000  2**12
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 12 .fini         00000010  00183474  00183474  00183474  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
 13 .rodata       0003f924  00183490  00183490  00183490  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 14 .ARM.extab    00000018  001c2db4  001c2db4  001c2db4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 15 .ARM.exidx    00000018  001c2dcc  001c2dcc  001c2dcc  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 16 .eh_frame     00000004  001c2de4  001c2de4  001c2de4  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
 17 .init_array   00000004  001d3b50  001d3b50  001c3b50  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 18 .fini_array   00000004  001d3b54  001d3b54  001c3b54  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 19 .data.rel.ro  00015378  001d3b58  001d3b58  001c3b58  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 20 .dynamic      00000130  001e8ed0  001e8ed0  001d8ed0  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 21 .got          0000079c  001e9000  001e9000  001d9000  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 22 .data         00000bcc  001e979c  001e979c  001d979c  2**2
                  CONTENTS, ALLOC, LOAD, DATA
 23 .bss          00002d8c  001ea368  001ea368  001da368  2**3
                  ALLOC
 24 .comment      0000009a  00000000  00000000  001da368  2**0
                  CONTENTS, READONLY
 25 .ARM.attributes 0000002e  00000000  00000000  001da402  2**0
                  CONTENTS, READONLY
 26 .debug_aranges 00000180  00000000  00000000  001da430  2**3
                  CONTENTS, READONLY, DEBUGGING
 27 .debug_info   00002872  00000000  00000000  001da5b0  2**0
                  CONTENTS, READONLY, DEBUGGING
 28 .debug_abbrev 00000427  00000000  00000000  001dce22  2**0
                  CONTENTS, READONLY, DEBUGGING
 29 .debug_line   00000c3a  00000000  00000000  001dd249  2**0
                  CONTENTS, READONLY, DEBUGGING
 30 .debug_frame  00000994  00000000  00000000  001dde84  2**2
                  CONTENTS, READONLY, DEBUGGING
 31 .debug_str    00001bed  00000000  00000000  001de818  2**0
                  CONTENTS, READONLY, DEBUGGING
 32 .debug_loc    00001e2a  00000000  00000000  001e0405  2**0
                  CONTENTS, READONLY, DEBUGGING
```

I tried all combinations of `UNW_ARM_UNWIND_METHOD` as well as tried building libopenssl with all possible flags that could facilitate stack unwiding that I'm aware for ARM: `-fno-omit-frame-pointer -funwind-tables -fasynchronous-unwind-tables -mapcs-frame -mtpcs-frame -mtpcs-leaf-frame`. Still no luck getting a frame past CRYPTO_zalloc.

Is there any other compiler/linker flag or something else that could be impeding this library to be properly unwinded? I'm absolutely out of ideas atm.

I would appreciate any help on this issue!

**Comment by bregma** [comment]
Your objdump shows an arm32 libcrypro, but you describe problems with an arm64 libunwind. Those two architectures are not ABI compatible when it comes to unwinding. Can you clarify more which architecture you're targeting?

**Comment by arthurep** [comment]
You are right. I miss took my platform for arm64 whereas everything is arm32.

This issue was due to an unrelated issue in my build system not rebuilding libopenssl with additional flags to unwind tables. Once I generated .ARM.exidx and .ARM.exidx with proper content, unwinding worked just fine.

Sorry for wasting your time and thank you for the support and for maintaining the project.
