### ISSUE TITLE
1.7 regression: Ltest-init-local-signal hangs on 32bit ARM and 64bit MIPS

### ISSUE THREAD

**Issue by AdrianBunk** [libunwind/libunwind#458]
Ltest-init-local-signal hangs (busyloops) in 1.7.0-rc2 on 32bit ARM and 64bit MIPS (it passes on these architectures in 1.6.2):
https://buildd.debian.org/status/fetch.php?pkg=libunwind&arch=armel&ver=1.7.0~rc2-1&stamp=1676295681&raw=0
https://buildd.debian.org/status/fetch.php?pkg=libunwind&arch=armhf&ver=1.7.0~rc2-1&stamp=1676304810&raw=0
https://buildd.debian.org/status/fetch.php?pkg=libunwind&arch=mips64el&ver=1.7.0~rc2-1&stamp=1676307149&raw=0

Attaching gdb on ARM shows it is somewhere below `arm_dwarf_callback`, e.g.

```
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0xf7d54d7e in __GI___libc_open (file=0x10154 "/lib/ld-linux-armhf.so.3", oflag=0)
    at ../sysdeps/unix/sysv/linux/open.c:43
#2  0xf7e2679c in elf_map_image (path=<optimized out>, ei=0xffb54838) at ./elfxx.h:77
#3  dwarf_find_eh_frame_section (info=info@entry=0xffb55920)
    at dwarf/Gfind_proc_info-lsb.c:539
#4  0xf7e27392 in _Uarm_dwarf_callback (info=0xffb55920, size=<optimized out>, 
    ptr=0xffb55988) at dwarf/Gfind_proc_info-lsb.c:642
#5  0xf7d967ce in __GI___dl_iterate_phdr (
    callback=0xf7e2715d <_Uarm_dwarf_callback>, data=data@entry=0xffb55988)
    at dl-iteratephdr.c:74
#6  0xf7e276a8 in _Uarm_dwarf_find_proc_info (as=0xf7e2e220 <local_addr_space>, 
    ip=4159127624, pi=0xffb566cc, need_unwind_info=1, arg=arg@entry=0xffb5a338)
    at dwarf/Gfind_proc_info-lsb.c:807
#7  0xf7e22374 in _Uarm_find_proc_info2 (as=0xf7e2e220 <local_addr_space>, 
    ip=4159127624, pi=0xffb566cc, need_unwind_info=1, arg=arg@entry=0xffb5a338, 
    methods=methods@entry=255) at arm/Gex_tables.c:521
#8  0xf7e223fc in _Uarm_find_proc_info (as=<optimized out>, ip=<optimized out>, 
    pi=<optimized out>, need_unwind_info=<optimized out>, arg=0xffb5a338)
    at arm/Gex_tables.c:551
#9  0xf7e246e2 in fetch_proc_info (c=c@entry=0xffb562a8, ip=<optimized out>)
    at dwarf/Gparser.c:473
#10 0xf7e25e22 in find_reg_state (sr=0xffb55c48, c=0xffb562a8)
    at dwarf/Gparser.c:1021
#11 _Uarm_dwarf_step (c=c@entry=0xffb562a8) at dwarf/Gparser.c:1066
#12 0xf7e21b16 in _Uarm_step (cursor=cursor@entry=0xffb562a8) at arm/Gstep.c:124
#13 0x000106aa in stepper (c=<optimized out>) at Ltest-init-local-signal.c:17
#14 handler (num=<optimized out>, info=<optimized out>, ucontext=<optimized out>)
    at Ltest-init-local-signal.c:35
#15 <signal handler called>
#16 foo (f=f@entry=0x0) at Ltest-init-local-signal-lib.c:5
#17 0x00010598 in main () at Ltest-init-local-signal.c:58
```

@Keno I've bisected this to commit 400b3f81.

Commenting out the following line fixes the test on 32bit ARM and 64bit MIPS: [DWARF_WHERE_CFA](https://github.com/libunwind/libunwind/pull/296/files#diff-0f5a23feddc05d252aefc4228075abe0a04394565973ab8a7e6a6dd56a31fbdcR512)

**Comment by Keno** [comment]
> Commenting out the following line fixes the test on 32bit ARM and 64bit MIPS: [DWARF_WHERE_CFA](https://github.com/libunwind/libunwind/pull/296/files#diff-0f5a23feddc05d252aefc4228075abe0a04394565973ab8a7e6a6dd56a31fbdcR512)

Do those architectures have a different default for their SP unwind?

**Comment by AdrianBunk** [comment]
```
include/libunwind-arm.h:    /* For ARM, the CFA is the value of SP (r13) at the call site in the
include/libunwind-arm.h-       previous frame.  */
include/libunwind-loongarch64.h:    /* For LoongArch64, the CFA is the value of SP (r3) at the call site in the
include/libunwind-loongarch64.h-       previous frame.  */
include/libunwind-mips.h:    /* For MIPS, the CFA is the value of SP (r29) at the call site in the
include/libunwind-mips.h-       previous frame.  */
include/libunwind-tilegx.h:  /* For TILEGX, the CFA is the value of SP (r54) at the call site in the
include/libunwind-tilegx.h-     previous frame.  */
```

```
      /* Don't bother reading SP from DWARF, CFA becomes new SP. */
      sp = cfa;
```

**Comment by bregma** [comment]
Missed this for 1.7. Needs a PR for the branch.
