### ISSUE TITLE
[GL]test-exc unit tests fail on ubuntu20.04_aarch64

### ISSUE THREAD

**Issue by bregma** [libunwind/libunwind#501]
The unit tests `Gtest-exc` and `Ltest-exc` fail on aarch64 Ubuntu 20.04 (and other hosts).

Detailed log file for Github Actions is as follows.
```
2023-05-08T18:21:55.1236534Z FAIL: Gtest-exc
2023-05-08T18:21:55.1236773Z ===============
2023-05-08T18:21:55.1236900Z 
2023-05-08T18:21:55.1237418Z  >_Uaarch64_init_mem_validate: using mincore to validate memory
2023-05-08T18:21:55.1237786Z  >unw_init_local_common: (cursor=0x55030485c8)
2023-05-08T18:21:55.1238154Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x0000005500001f1c, cfa=0x0000005503048180))
2023-05-08T18:21:55.1239210Z  >_Uaarch64_dwarf_search_unwind_table: e->fde_offset = 3a4, segbase = 550001583c, debug_frame_base = 0, fde_addr = 5500015be0
2023-05-08T18:21:55.1239622Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1239952Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x0000005500002124, cfa=0x0000005503048da0))
2023-05-08T18:21:55.1240568Z  >_Uaarch64_dwarf_search_unwind_table: e->fde_offset = 454, segbase = 550001583c, debug_frame_base = 0, fde_addr = 5500015c90
2023-05-08T18:21:55.1240971Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1241298Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x0000005500002218, cfa=0x0000005503048dc0))
2023-05-08T18:21:55.1241912Z  >_Uaarch64_dwarf_search_unwind_table: e->fde_offset = 478, segbase = 550001583c, debug_frame_base = 0, fde_addr = 5500015cb4
2023-05-08T18:21:55.1242303Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1242645Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048df0))
2023-05-08T18:21:55.1243229Z  >_Uaarch64_dwarf_search_unwind_table: e->fde_offset = 478, segbase = 550001583c, debug_frame_base = 0, fde_addr = 5500015cb4
2023-05-08T18:21:55.1243622Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1243959Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048e20))
2023-05-08T18:21:55.1244268Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1245340Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048e50))
2023-05-08T18:21:55.1245664Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1246000Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048e80))
2023-05-08T18:21:55.1246307Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1246657Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048eb0))
2023-05-08T18:21:55.1246982Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1247303Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048ee0))
2023-05-08T18:21:55.1247626Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1247961Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048f10))
2023-05-08T18:21:55.1248266Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1248595Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048f40))
2023-05-08T18:21:55.1248917Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1249561Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048f70))
2023-05-08T18:21:55.1249866Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1250197Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048fa0))
2023-05-08T18:21:55.1250711Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1251039Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503048fd0))
2023-05-08T18:21:55.1251363Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1251696Z  >_Uaarch64_step: (cursor=0x55030485c8, ip=0x00000055000021b8, cfa=0x0000005503049000))
2023-05-08T18:21:55.1252000Z  >_Uaarch64_step: dwarf_step()=1
2023-05-08T18:21:55.1252290Z  >_Uaarch64_resume: (cursor=0x55030485c8)
2023-05-08T18:21:55.1252589Z  >access_reg: bad register number 33
2023-05-08T18:21:55.1252950Z  >_Uaarch64_access_reg: Reading from ra sign state not supported: 34
2023-05-08T18:21:55.1253304Z  >_Uaarch64_access_reg: bad register number 35
2023-05-08T18:21:55.1253641Z  >_Uaarch64_access_reg: bad register number 36
2023-05-08T18:21:55.1253965Z  >_Uaarch64_access_reg: bad register number 37
2023-05-08T18:21:55.1254849Z  >_Uaarch64_access_reg: bad register number 38
2023-05-08T18:21:55.1255221Z  >_Uaarch64_access_reg: bad register number 39
2023-05-08T18:21:55.1256374Z  >_Uaarch64_access_reg: bad register number 40
2023-05-08T18:21:55.1256696Z  >_Uaarch64_access_reg: bad register number 41
2023-05-08T18:21:55.1257010Z  >_Uaarch64_access_reg: bad register number 42
2023-05-08T18:21:55.1257331Z  >_Uaarch64_access_reg: bad register number 43
2023-05-08T18:21:55.1257634Z  >_Uaarch64_access_reg: bad register number 44
2023-05-08T18:21:55.1257948Z  >_Uaarch64_access_reg: bad register number 45
2023-05-08T18:21:55.1258309Z  >uc_addr: Accessing VG register from context is not supported
2023-05-08T18:21:55.1258642Z  >access_reg: bad register number 46
2023-05-08T18:21:55.1258956Z  >_Uaarch64_access_reg: bad register number 47
2023-05-08T18:21:55.1259280Z  >_Uaarch64_access_reg: bad register number 48
2023-05-08T18:21:55.1259600Z  >_Uaarch64_access_reg: bad register number 49
2023-05-08T18:21:55.1259907Z  >_Uaarch64_access_reg: bad register number 50
2023-05-08T18:21:55.1260220Z  >_Uaarch64_access_reg: bad register number 51
2023-05-08T18:21:55.1260543Z  >_Uaarch64_access_reg: bad register number 52
2023-05-08T18:21:55.1260843Z  >_Uaarch64_access_reg: bad register number 53
2023-05-08T18:21:55.1261158Z  >_Uaarch64_access_reg: bad register number 54
2023-05-08T18:21:55.1261472Z  >_Uaarch64_access_reg: bad register number 55
2023-05-08T18:21:55.1261772Z  >_Uaarch64_access_reg: bad register number 56
2023-05-08T18:21:55.1262083Z  >_Uaarch64_access_reg: bad register number 57
2023-05-08T18:21:55.1262396Z  >_Uaarch64_access_reg: bad register number 58
2023-05-08T18:21:55.1262693Z  >_Uaarch64_access_reg: bad register number 59
2023-05-08T18:21:55.1263014Z  >_Uaarch64_access_reg: bad register number 60
2023-05-08T18:21:55.1263329Z  >_Uaarch64_access_reg: bad register number 61
2023-05-08T18:21:55.1263648Z  >_Uaarch64_access_reg: bad register number 62
2023-05-08T18:21:55.1263953Z  >_Uaarch64_access_reg: bad register number 63
2023-05-08T18:21:55.1264271Z *** stack smashing detected ***: terminated
2023-05-08T18:21:55.1264716Z FAIL Gtest-exc (exit status: 134)
```

Gdb traceback is as follows.
```
Program received signal SIGSEGV, Segmentation fault.
0x000000550000209c in _ULaarch64_access_reg (c=c@entry=0x550283c208, reg=reg@entry=46, valp=valp@entry=0x550283bd88, write=write@entry=0) at ../../src/aarch64/Gregs.c:126
126                 *valp = (val16 * 8) / 64;
#0  0x000000550000209c in _ULaarch64_access_reg (c=c@entry=0x550283c208, reg=reg@entry=46, valp=valp@entry=0x550283bd88, write=write@entry=0) at ../../src/aarch64/Gregs.c:126
#1  0x0000005500002424 in establish_machine_state (c=0x550283c208) at ../../src/aarch64/Gresume.c:173
#2  _ULaarch64_resume (cursor=0x550283c208) at ../../src/aarch64/Gresume.c:194
#3  0x0000005500001730 in raise_exception () at ../../tests/Gtest-exc.c:90
#4  0x0000005500001864 in b (n=<optimized out>) at ../../tests/Gtest-exc.c:146
#5  0x0000005500001960 in a (n=0) at ../../tests/Gtest-exc.c:120
#6  0x0000005500001900 in a (n=1) at ../../tests/Gtest-exc.c:118
#7  0x0000005500001900 in a (n=2) at ../../tests/Gtest-exc.c:118
#8  0x0000005500001900 in a (n=3) at ../../tests/Gtest-exc.c:118
#9  0x0000005500001900 in a (n=4) at ../../tests/Gtest-exc.c:118
#10 0x0000005500001900 in a (n=5) at ../../tests/Gtest-exc.c:118
#11 0x0000005500001900 in a (n=6) at ../../tests/Gtest-exc.c:118
#12 0x0000005500001900 in a (n=7) at ../../tests/Gtest-exc.c:118
#13 0x0000005500001900 in a (n=8) at ../../tests/Gtest-exc.c:118
#14 0x0000005500001900 in a (n=9) at ../../tests/Gtest-exc.c:118
#15 0x0000005500001900 in a (n=10) at ../../tests/Gtest-exc.c:118
#16 0x0000005500001900 in a (n=11) at ../../tests/Gtest-exc.c:118
#17 0x0000005500001900 in a (n=12) at ../../tests/Gtest-exc.c:118
#18 0x0000005500001900 in a (n=13) at ../../tests/Gtest-exc.c:118
#19 0x0000005500001424 in main (argc=<optimized out>, argv=<optimized out>) at ../../tests/Gtest-exc.c:168
```

**Comment by bregma** [comment]
Closed by PR #503
