### ISSUE TITLE
riscv64-linux fails Ltest-cxx-exceptions

### ISSUE THREAD

**Issue by bregma** [libunwind/libunwind#531]
This unit test is failing consistently (Ubuntu 20.04, qemu-riscv64-static).

GDB traceback just gives this.
```
Reading symbols from /home/swebb/projects/libunwind/bregma/linux-riscv64/tests/Ltest-cxx-exceptions...
Remote debugging using localhost:1234
Reading symbols from /usr/riscv64-linux-gnu/lib/ld-linux-riscv64-lp64d.so.1...
(No debugging symbols found in /usr/riscv64-linux-gnu/lib/ld-linux-riscv64-lp64d.so.1)
0x0000004002830f30 in ?? () from /usr/riscv64-linux-gnu/lib/ld-linux-riscv64-lp64d.so.1
Continuing.

Program received signal SIGABRT, Aborted.
0x0000004002a3e074 in raise () from /usr/riscv64-linux-gnu/lib/libc.so.6
#0  0x0000004002a3e074 in raise () from /usr/riscv64-linux-gnu/lib/libc.so.6
#1  0x0000004002a2ecce in abort () from /usr/riscv64-linux-gnu/lib/libc.so.6
Backtrace stopped: frame did not save the PC
```

**Comment by bregma** [comment]
Duplicate of #519
