### ISSUE TITLE
Segfault in `_ULx86_64_dwarf_callback` while unwinding using `uwn_backtrace2`

### ISSUE THREAD

**Issue by gleocadie** [libunwind/libunwind#537]
Our [.NET profiler](https://github.com/DataDog/dd-trace-dotnet/) uses libunwind to collect callstacks. We rely on `unw_backtrace2` to get the IPs and in another component we do the symbols resolution.

One of our customer experiences crash (~1 every 24h) and they managed to send us a crash dump.
Here is the callstack of the segfault:

```
(gdb) bt -full
#0  0x000075e1a766474b in _ULx86_64_dwarf_callback () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#1  0x000075e1ab663a15 in __GI___dl_iterate_phdr (callback=callback@entry=0x75e1a76644a0 <_ULx86_64_dwarf_callback>, data=data@entry=0x75e128fdb530) at dl-iteratephdr.c:75
        __clframe = {__cancel_routine = <optimized out>, __cancel_arg = 0x0, __do_it = 1, __cancel_type = <optimized out>}
        nloaded = 29
        ns = <optimized out>
        caller = <optimized out>
        l = 0x5d7375bbc700
        info = {dlpi_addr = 129612094119936, dlpi_name = 0x5d7375c2e090 "/usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libcoreclr.so", dlpi_phdr = 0x75e1aad42040, dlpi_phnum = 11, dlpi_adds = 30, dlpi_subs = 1, dlpi_tls_modid = 7,
          dlpi_tls_data = 0x75ded82fe490}
        ret = 0
#2  0x000075e1aba621a5 in dl_iterate_phdr (callback=0x75e1a76644a0 <_ULx86_64_dwarf_callback>, data=0x75e128fdb530) at /project/profiler/src/ProfilerEngine/Datadog.Linux.ApiWrapper/functions_to_wrap.c:73
        result = <optimized out>
#3  0x000075e1a7664a95 in _ULx86_64_dwarf_find_proc_info () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#4  0x000075e1a76611f6 in _ULx86_64_dwarf_step () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#5  0x000075e1a765f7d9 in _ULx86_64_step () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#6  0x000075e1a76603ff in _ULx86_64_tdep_trace () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#7  0x000075e1a765f094 in unw_backtrace2 () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#8  0x000075e1a75ee8da in LinuxStackFramesCollector::CollectCallStackCurrentThread(void*) () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#9  0x000075e1a75ede63 in LinuxStackFramesCollector::CollectStackSampleSignalHandler(int, siginfo_t*, void*) () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#10 0x000075e1a75efe91 in ProfilerSignalManager::SignalHandler(int, siginfo_t*, void*) () from /app/publish/datadog/linux-x64/./Datadog.Profiler.Native.so
No symbol table info available.
#11 <signal handler called>
No locals.
#12 0x000075e1ab359ea0 in ?? () from /usr/share/dotnet/shared/Microsoft.NETCore.App/7.0.5/libcoreclr.so
No symbol table info available.
#13 <signal handler called>
No locals.
#14 0x000075e13dcb928a in ?? ()
No symbol table info available.
#15 0x000075def9a97100 in ?? ()
No symbol table info available.
#16 0x000075df5fd4a930 in ?? ()
No symbol table info available.
#17 0x0000000000000000 in ?? ()
```

It seems to crash in `_ULx86_64_dwarf_callback`. I also noticed that the thread was already in a signal handler (frames 11 nd 13). Not sure if it can be an issue but worth noting.

Are you able to help me in investigating this crash please ? what would you need ? Should I rebuild with `-g` ? 

Thanks in advance for your help.

**Comment by gleocadie** [comment]
I'll close it for now. The customer did not get back to us.
