### ISSUE TITLE
QNX test error: Memory fault (core dumped) 

### ISSUE THREAD

**Issue by tangzhiqiang3** [libunwind/libunwind#646]
QNX 7.0:
```shell
./configure --host=aarch64-unknown-nto-qnx7.0.0 --prefix=${INSTALL_PATH} --with-rpath=${QNX_HOST}/usr/ \
       CC=aarch64-unknown-nto-qnx7.0.0-gcc CXX="aarch64-unknown-nto-qnx7.0.0-g++" \
       --disable-syscall --enable-log --enable-lazy-lock --disable-initial-exec-tls \
       CXXFLAGS="-fpic  -D__QNX__"
make clean
make -j32  && make install
````

test src: 
```c
#include <stdio.h>
#define UNW_LOCAL_ONLY
#include <libunwind.h>

void do_backtrace()
{
    unw_cursor_t    cursor;
    unw_context_t   context;

    unw_getcontext(&context);
    unw_init_local(&cursor, &context);

    while (unw_step(&cursor) > 0) {
        unw_word_t  offset, pc;
        char        fname[64];

        unw_get_reg(&cursor, UNW_REG_IP, &pc);

        fname[0] = '\0';
        (void) unw_get_proc_name(&cursor, fname, sizeof(fname), &offset);

        printf ("%p : (%s+0x%x) [%p]\n", pc, fname, offset, pc);
    }
}

int main()
{
    do_backtrace();

}
```
run: 
```shell
# ./libunwind_backtrace 
162e641e54 : (main+0xc) [162e641e54]
162e641be8 : (_start+0x88) [162e641be8]

Process 2014666779 (libunwind_backtrace) terminated SIGSEGV code=1 fltno=11 ip=00000016efcab9f0(/var/data/demo_test/libunwind.so.9@_ULaarch64_step+0x0000000000000190) mapaddr=00000000000059f0. ref=ffffff8099e302f0
Memory fault (core dumped) 
````
GDB debug:

```shell
(gdb) bt
#0  dwarf_get (c=<optimized out>, val=<optimized out>, loc=...) at ../include/tdep-aarch64/libunwind_i.h:156
#1  _ULaarch64_step (cursor=0x2c96761388) at aarch64/Gstep.c:488
#2  0x00000027c96e0dc4 in do_backtrace () at libunwind_backtrace.c:13
#3  0x00000027c96e0e08 in main () at libunwind_backtrace.c:28
(gdb) frame 2
#2  0x00000027c96e0dc4 in do_backtrace () at     libunwind_backtrace.c:13
13          while (unw_step(&cursor) > 0) {
(gdb) frame 3
#3  0x00000027c96e0e08 in main () at libunwind_backtrace.c:28
28          do_backtrace();

````
Locate to function unw_step in for src/aarch64/Gstep.c  error!!

now revert : d7ca80c5126e65031251c778cd13e4e6a097fec6 change can solve error.
But  only one stack can be seen!  Please fix unw_step function bug ??

**Comment by bregma** [comment]
@tangzhiqiang3 does the fix in PR #659 fix your problem?
