### ISSUE TITLE
unw_address_is_valid failed to validate incorrect address

### ISSUE THREAD

**Issue by dqminh** [libunwind/libunwind#661]
Hi,

We had a coredump when unwinding, with the backtrace looks like

```
#0  access_mem (as=<optimized out>, addr=140196322476030, val=<optimized out>, write=<optimized out>, arg=<optimized out>) at x86_64/Ginit.c:94
#1  0x00007f836b32e3ef in _ULx86_64_step (cursor=cursor@entry=0x7ffd435c0a20) at x86_64/Gstep.c:240
#2  0x00007f836b32edce in trace_init_addr (rsp=<optimized out>, rbp=<optimized out>, rip=<optimized out>, cfa=<optimized out>, cursor=0x7ffd435c0a20,
    f=0x7f809e68e9d0) at x86_64/Gtrace.c:249
#3  trace_lookup (rsp=<optimized out>, rbp=<optimized out>, rip=<optimized out>, cfa=<optimized out>, cache=0x7f836b352fe0, cursor=0x7ffd435c0a20)
    at x86_64/Gtrace.c:331
#4  _ULx86_64_tdep_trace (cursor=cursor@entry=0x7ffd435c0a20, buffer=buffer@entry=0x7f832aa316b8, size=size@entry=0x7ffd435c0644) at x86_64/Gtrace.c:449
#5  0x00007f836b32c4ec in unw_backtrace (buffer=0x7f832aa316b8, size=size@entry=128) at mi/backtrace.c:70
#6  0x00005583e78fbcee in prof_backtrace_impl (vec=<optimized out>, len=0x7ffd435c1288, max_len=<optimized out>) at src/prof_sys.c:60
....
```

Specifically, we have:

```
(gdb) x/8b addr
0x7f81fffffffe: ""
0x7f81ffffffff: ""
0x7f8200000000: <error: Cannot access memory at address 0x7f8200000000>
0x7f8200000000: <error: Cannot access memory at address 0x7f8200000000>
0x7f8200000000: <error: Cannot access memory at address 0x7f8200000000>
0x7f8200000000: <error: Cannot access memory at address 0x7f8200000000>
0x7f8200000000: <error: Cannot access memory at address 0x7f8200000000>
0x7f8200000000: <error: Cannot access memory at address 0x7f8200000000>
```

Looking specifically at the `unw_address_is_valid` function, i'm not sure that it's checking the address correctly, specifically this part

```
// If we're still on the same page, we're done.
size_t stride = len-1 < (size_t) unw_page_size ? len-1 : (size_t) unw_page_size;
len -= stride;
addr += stride;
if (unw_page_start (addr) == unw_page_start (lastbyte))
        break;
```

if for any reason, `addr` and `lastbyte` are on 2 different consecutive pages, then we skip the check for `lastbyte` page, which is incorrect. I think the check should be

```
// If we're still on the same page, we're done.
if (unw_page_start (addr) == unw_page_start (lastbyte))
        break;
size_t stride = len-1 < (size_t) unw_page_size ? len-1 : (size_t) unw_page_size;
len -= stride;
addr += stride;
```

**Comment by bregma** [comment]
Agreed.
